spring:
  application:
    name: blog-app
  datasource:
    url: ${DB_URL:jdbc:mysql://localhost:3306/blog_app?createDatabaseIfNotExist=true&allowPublicKeyRetrieval=true&useSSL=false&serverTimezone=UTC}
    username: ${DB_USER:root}
    password: ${DB_PASS:Dev@Null}
  jpa:
    properties:
      hibernate:
        ddl-auto: update
    generate-ddl: true
  sql:
    init:
      mode: always
logging:
  level:
#    org.springframework: off
    org.hibernate: off
    com.zaxxer: off
    com.codewithevans: [ DEBUG, ERROR, WARN, INFO ]
springdoc:
  swagger-ui:
    tags-sorter: alpha
    operations-sorter: alpha
  writer-with-order-by-keys: true
app:
  admin-user: ${ADMIN_USER:admin@admin.com}
  admin-pass: ${ADMIN_PASS:P@$$w0rd}
  jwt-secret: ${JWT_SECRET:super_secret_key_here}
  issuer: ${JWT_ISSUER:http://localhost:${server.port}}
  expires-in: ${JWT_EXPIRES_IN:60}
  pass-expiry: ${PASS_EXPIRY:30}
server:
  port: ${SERVER_PORT:8080}